version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py collectstatic --noinput &&
             gunicorn cms_project.wsgi:application --bind 0.0.0.0:8000 --workers=2"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=cms_project.settings
      - DATABASE_URL=postgres://wagtail:wagtailpassword@db:5432/wagtail
      - PYTHONPATH=/app
    volumes:
      - ./cms_project:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: wagtailpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: